apiVersion: v1
kind: Secret
metadata:
  name: tap-cert
  namespace: cert-manager
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-cert  # Replace with a name of your choice
  namespace: cert-manager
spec:
  commonName: "*.tap1.tanzu.rocks" # Wildcard Entry for your domain
  dnsNames:
    - "*.tap1.tanzu.rocks"
  issuerRef:
    name: letsencrypt-dynu-tap   # This should match the issuer you defined earlier
    kind: ClusterIssuer
  secretName: tap-cert # Secret name where the resulting certificate is saved in

