apiVersion: v1
data:
  api-key: NFRmVldYNDZjV2JVVjVlMzVWZWNkWlRlNTJlNjZjNTQ=
kind: Secret
metadata:
  name: dynu-secret
  namespace: cert-manager
type: Opaque

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dynu-tap
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory              # Use this for prod
    #server: https://acme-staging-v02.api.letsencrypt.org/directory    # Use this for staging/testing


    # Email address used for ACME registration
    email: davidlloyd0@gmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: tap-encrypt-secret

    solvers:
      - dns01:
          cnameStrategy: Follow
          webhook:
            groupName: com.github.dopingus.cert-manager-webhook-dynu
            solverName: dynu
            config:
              secretName: dynu-secret
        selector:
          dnsNames:
          - 'tap-gui.tap3.tanzu.rocks'
          - '*.apps.tap3.tanzu.rocks'
          - 'appliveview.view.tap3.tanzu.rocks'
          - 'learningcenter.tap3.tanzu.rocks'
      - http01:
          ingress:
            class: contour      

---
