apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: cert-manager-dynu-webhook
    meta.helm.sh/release-namespace: default
  labels:
    app: dynu-webhook
    app.kubernetes.io/managed-by: Helm
    chart: dynu-webhook-0.1.1
    heritage: Helm
    release: cert-manager-dynu-webhook
  name: cert-manager-dynu-webhook:flowcontrol-solver
rules:
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - 'prioritylevelconfigurations'
      - 'flowschemas'
    verbs:
      - 'list'
      - 'watch'
---      
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: cert-manager-dynu-webhook
    meta.helm.sh/release-namespace: cert-manager
  labels:
    app: dynu-webhook
    app.kubernetes.io/managed-by: Helm
    chart: dynu-webhook-0.1.1
    heritage: Helm
    release: cert-manager-dynu-webhook
  name: cert-manager-dynu-webhook:flowcontrol-solver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-dynu-webhook:flowcontrol-solver
subjects:
- kind: ServiceAccount
  name: cert-manager-dynu-webhook
  namespace: default