# rds.class.yaml

---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: aws-rds-mysql
spec:
  description:
    short: Amazon AWS RDS MySQL
  provisioner:
    crossplane:
      compositeResourceDefinition: xmysqlinstances.database.rds.apa.org
