apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    vpc: dbsn_dataservices
    provider: aws
  name: xbucket.s3.aws.apa.org
spec:
  compositeTypeRef:
    apiVersion: s3.aws.apa.org/v1alpha1
    kind: XBucket
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
  - base:
      name: s3-bucket
      apiVersion: s3.aws.upbound.io/v1beta1
      kind: Bucket
      metadata:
        labels:
          xbucket.s3.aws.apa.org/bucketId: id
      spec:
        deletionPolicy: Delete
        forProvider:
          region: ap-southeast-2
          tags:
            owner: apa
            service: unset     
        providerConfigRef:
          name: aws-config   
        writeConnectionSecretToRef:
          namespace: crossplane-system
    connectionDetails:
      - name: bucket_name
        fromConnectionSecretKey: endpoint
    patches:
    - fromFieldPath: metadata.uid
      toFieldPath: metadata.labels.xbucket.s3.aws.apa.org/bucketId
      transforms:
      - string:
          fmt: '%s-id'
          type: Format
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-s3-connection'
          type: Format
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: status.name
      type: ToCompositeFieldPath
    - fromFieldPath: status.atProvider.arn
      toFieldPath: status.bucketArn
      type: ToCompositeFieldPath
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.region
      transforms:
      - type: map
        map:
          sydney: ap-southeast-2
          singapore: ap-southeast-1
  - base:
      name: s3-accesspoint
      apiVersion: s3control.aws.upbound.io/v1beta1
      kind: AccessPoint
      metadata:
        labels:
          xbucket.s3.aws.apa.org/bucketId: id
      spec:
        forProvider:
          region: ap-southeast-2
          bucketSelector:
            matchControllerRef: true
        providerConfigRef:
          name: aws-config   
        writeConnectionSecretToRef:
          namespace: crossplane-system
    patches:
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-s3ap'
          type: Format
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.uid
      toFieldPath: metadata.labels.xbucket.s3.aws.apa.org/bucketId
    - fromFieldPath: metadata.uid
      toFieldPath: spec.forProvider.name
      transforms:
      - string:
          fmt: '%s-ap'
          type: Format
        type: string
  - base:
      name: s3-bucketaccess
      apiVersion: s3.aws.upbound.io/v1beta1
      kind: BucketPublicAccessBlock
      spec:
        forProvider:
          region: ap-southeast-2
          blockPublicAcls: false
          blockPublicPolicy: false
          bucketSelector:
            matchControllerRef: true
        providerConfigRef:
          name: aws-config   
    patches:
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.region
      transforms:
      - type: map
        map:
          sydney: ap-southeast-2
          singapore: ap-southeast-1
  - base:
      name: s3-bucketpolicy
      apiVersion: s3.aws.upbound.io/v1beta1
      kind: BucketPolicy
      spec:
        forProvider:
          region: ap-southeast-2
          policy: ''
          bucketSelector:
            matchControllerRef: true
        providerConfigRef:
          name: aws-config   
    patches:
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.region
      transforms:
      - type: map
        map:
          sydney: ap-southeast-2
          singapore: ap-southeast-1
    - fromFieldPath: status.bucketArn
      toFieldPath: spec.forProvider.policy
      transforms:
        - type: string
          string:
            fmt: >
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Sid": "AllowGetObject",
                    "Principal": {
                      "AWS": "*"
                    },
                    "Effect": "Allow",
                    "Action": [
                      "s3:*"
                    ],
                    "Resource": [
                      "%s/*"
                    ],
                    "Condition": {
                      "StringEquals": {
                        "aws:PrincipalOrgID": [
                          "o-08i2i7oky6"
                        ]
                      }
                    }
                  }
                ]
              }
  # - base:
  #     apiVersion: iam.aws.upbound.io/v1beta1
  #     kind: User
  #     spec:
  #       deletionPolicy: Delete
  #       writeConnectionSecretToRef:
  #         namespace: crossplane-system
  #       forProvider:
  #         path: "/"
  #       providerConfigRef:
  #         name: aws-config
  #   patches:
  #     - fromFieldPath: status.name
  #       toFieldPath: metadata.name
  #       transforms:
  #       - type: string
  #         string:
  #           fmt: "%s-user"
  #     - fromFieldPath: status.name
  #       toFieldPath: spec.writeConnectionSecretToRef.name
  #       transforms:
  #       - type: string
  #         string:
  #           fmt: "%s-user-details"
  # - base:
  #     apiVersion: iam.aws.upbound.io/v1beta1
  #     kind: UserPolicyAttachment
  #     spec:
  #       deletionPolicy: Delete
  #       writeConnectionSecretToRef:
  #         namespace: crossplane-system
  #       forProvider: {}
  #       providerConfigRef:
  #         name: aws-config
  #   patches:
  #     - fromFieldPath: status.name
  #       toFieldPath: metadata.name
  #       transforms:
  #       - type: string
  #         string:
  #           fmt: "%s-user-bucket-policy"
  #     - fromFieldPath: status.bucketArn
  #       toFieldPath: "spec.forProvider.policyArnRef.name"
  #       transforms:
  #       - type: string
  #         string:
  #           fmt: "%s-bucket-access-policy"
  #     - fromFieldPath: "status.name"
  #       toFieldPath: "spec.forProvider.userNameRef.name"
  #       transforms:
  #       - type: string
  #         string:
  #           fmt: "%s-user"
  #     - fromFieldPath: status.name
  #       toFieldPath: spec.writeConnectionSecretToRef.name
  #       transforms:
  #       - type: string
  #         string:
  #           fmt: "%s-user-details"
  # - base:
  #     apiVersion: iam.aws.upbound.io/v1beta1
  #     kind: AccessKey
  #     spec:
  #       deletionPolicy: Delete
  #       writeConnectionSecretToRef:
  #         namespace: crossplane-system
  #       forProvider: {}
  #       providerConfigRef:
  #         name: aws-config
  #   patches:
  #     - fromFieldPath: status.name
  #       toFieldPath: metadata.name
  #       transforms:
  #       - type: string
  #         string:
  #           fmt: "%s-user-access-key"
  #     - fromFieldPath: status.name
  #       toFieldPath: spec.forProvider.userNameRef.name
  #       transforms:
  #       - type: string
  #         string:
  #           fmt: "%s-user"
  #     - fromFieldPath: status.name
  #       toFieldPath: spec.writeConnectionSecretToRef.name
  #       transforms:
  #       - type: string
  #         string:
  #           fmt: "%s-user-access-key"
  #   connectionDetails:
  #     - name: account_id
  #       fromConnectionSecretKey: username
  #     - name: account_key
  #       fromConnectionSecretKey: password
  