apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.s3.aws.apa.org
spec:
  group: s3.aws.apa.org
  names:
    kind: XBucket
    plural: xbuckets
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
                enum:
                  - sydney
                  - singapore
                description: |
                  Region where DB instance will be deployed
                default: sydney
            required:
              - region
    served: true
    referenceable: true
  claimNames:
    kind: Bucket
    plural: buckets
    