# provider-family-aws.yaml

---

# The AWS "family" Provider
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v0.42.0
  controllerConfigRef:
    name: provider-aws-controller-config

---

# The AWS RDS Provider
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-rds-config
spec:
  package: xpkg.upbound.io/upbound/provider-aws-rds:v0.42.0
  controllerConfigRef:
    name: provider-aws-controller-config

---

# The AWS S3 Provider
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3-config
spec:
  package: xpkg.upbound.io/upbound/provider-aws-s3:v0.42.0
  controllerConfigRef:
    name: provider-aws-controller-config

---

apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws-controller-config