apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: registry-credentials
spec:
  fromNamespace: tap-install

--- 

apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-registry
spec:
  fromNamespace: tap-install

--- 

apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-auth
spec:
  fromNamespace: tap-install

--- 

apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: supply-chain-oci-store-credentials
spec:
  fromNamespace: tap-install


--- 

apiVersion: v1
kind: Secret
metadata:
  name: pivnet-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: lloydd@vmware.com
  password: Sunsh1ne!
