
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    vpc: dbsn_dataservices
    provider: "aws"
  name: xrdsinstances.database.rds.apa.org
spec:
  compositeTypeRef:
    apiVersion: database.rds.apa.org/v1alpha1
    kind: XRDSInstance
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
  - base:
      apiVersion: rds.aws.upbound.io/v1beta1
      kind: Instance
      spec:
        forProvider:
          instanceClass: db.t3.micro
          autoGeneratePassword: true
          passwordSecretRef:
            key: password
            namespace: crossplane-system
          engine: mysql
          dbName: firstdb
          engineVersion: "8.0.34"
          allocatedStorage: 20
          username: dbadmin
          publiclyAccessible: true
          region: ap-southeast-2
          skipFinalSnapshot: true
          vpcSecurityGroupIds: [sg-07ebdf8570e72e4e8,sg-0647c59f867d018ed]
          dbSubnetGroupName: dbsn_dataservices
          tags:
            owner: "apa"
            service: "unset"
        providerConfigRef:
          name: aws-config   
        writeConnectionSecretToRef:
          namespace: crossplane-system
    connectionDetails:
    - name: provider
      value: aws
    - name: type
      fromFieldPath: spec.forProvider.tags['provider']
    - name: database
      fromFieldPath: spec.forProvider.dbName
    - fromConnectionSecretKey: username
    - fromConnectionSecretKey: password
    - name: host
      fromConnectionSecretKey: endpoint
    - fromConnectionSecretKey: port
    name: instance
    patches:
    - fromFieldPath: metadata.uid
      toFieldPath: spec.forProvider.passwordSecretRef.name
      transforms:
      - string:
          fmt: '%s-rds-pw'
          type: Format
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-rds'
          type: Format
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: spec.storageGB
      toFieldPath: spec.forProvider.allocatedStorage
    - fromFieldPath: spec.dbName
      toFieldPath: spec.forProvider.dbName
    - fromFieldPath: spec.dbSubnetGroupName
      toFieldPath: spec.forProvider.dbSubnetGroupName
    - fromFieldPath: spec.publiclyAccessible
      toFieldPath: spec.forProvider.publiclyAccessible
      transforms:
      - type: convert
        convert:
          toType: bool
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.region
      transforms:
      - type: map
        map:
          sydney: ap-southeast-2
          singapore: ap-southeast-1
    - fromFieldPath: spec.size
      toFieldPath: spec.forProvider.instanceClass
      transforms:
      - type: map
        map:
          micro: db.t3.micro
          small: db.t3.small
          medium: db.t3.medium
          large: db.t3.large
    - fromFieldPath: spec.dbType
      toFieldPath: spec.forProvider.engine
      transforms:
      - type: map
        map:
          mysql: mysql
          postgres: postgres
    - fromFieldPath: spec.dbType
      toFieldPath: spec.forProvider.engineVersion
      transforms:
      - type: map
        map:
          mysql: '8.0.34'
          postgres: '13.7'
    - fromFieldPath: spec.region
      toFieldPath: spec.forProvider.dbSubnetGroupName
      transforms:
      - type: map
        map:
          sydney: dbsn_dataservices
          singapore: dbsn_dataservices
    - fromFieldPath: spec.dbType
      toFieldPath: spec.writeConnectionSecretToRef.type
      transforms:
      - type: map
        map:
          mysql: "mysql"
          postgres: "postgres"
    - fromFieldPath: "spec.dbType"
      toFieldPath: "spec.forProvider.tags['provider']"
      transforms:
      - type: map
        map:
          mysql: "mysql"
          postgres: "postgresql"
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: spec.region
          - fromFieldPath: spec.dbType
        strategy: string
        string:
          fmt: "%s-%s"
      toFieldPath: spec.forProvider.tags['service']
    - type: ToCompositeFieldPath
      fromFieldPath: spec.forProvider.tags['service']
      toFieldPath: status.operations.servicetype
    - fromFieldPath: status.operations.servicetype
      toFieldPath: spec.forProvider.vpcSecurityGroupIds
      transforms:
      - type: map
        map:
          sydney-mysql: [sg-07ebdf8570e72e4e8,sg-0647c59f867d018ed]
          sydney-postgres: [sg-07ebdf8570e72e4e8,sg-0d6bd77db201af85f]
          singapore-mysql: [sg-0c5c3d3010f37b05e,sg-0a339b1c60c948327]
          singapore-postgres: [sg-0c5c3d3010f37b05e,sg-0882f511ebb5a4c0a]    


