---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrdsinstances.database.rds.apa.org
spec:
  claimNames:
    kind: RDSInstance
    plural: rdsinstances
  connectionSecretKeys:
  - type
  - provider
  - host
  - port
  - database
  - username
  - password
  group: database.rds.apa.org
  names:
    kind: XRDSInstance
    plural: xrdsinstances
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: |
              This specification defines how an RDS Instance is deployed
            properties:
              storageGB:
                type: integer
                default: 20
                description: |
                  Size in GB of storage space to assign to DB instance
              dbName:
                type: string
                default: mydb
                description: |
                  Name to assign to the default database created in the instance
              region:
                type: string
                enum:
                  - sydney
                  - singapore
                description: |
                  Region where DB instance will be deployed
                default: sydney
              size:
                type: string
                enum:
                  - micro
                  - small
                  - medium
                  - large
                description: |
                  Machine size for the DB instance
                default: micro
              publiclyAccessible:
                type: string
                default: 'true'
                description: |
                  Defines if the DB instances will be assigned a public DNS and IP address
              dbType:
                type: string
                default: mysql
                enum:
                 - mysql
                 - postgres
            type: object
        type: object
    served: true

                
